### ISSUE TITLE
regression when switching from asyncore to asyncio

### ISSUE THREAD

**Issue by leggewie** [mvo5/squid-deb-proxy#8]
commit bd87b267c1bf6 from PR1 that switched from asyncore to asyncio lib unfortunately [introduces a regression](https://bugs.launchpad.net/ubuntu/+source/squid-deb-proxy/+bug/2002562) when a proxy is present but inactive on the same machine.

```
$ /usr/share/squid-deb-proxy-client/apt-avahi-discover
Traceback (most recent call last):
  File "/usr/share/squid-deb-proxy-client/apt-avahi-discover", line 148, in <module>
    address = get_proxy_host_port_from_avahi()
  File "/usr/share/squid-deb-proxy-client/apt-avahi-discover", line 131, in get_proxy_host_port_from_avahi
    asyncio.run(asyncio.wait_for(gather_hosts(), timeout=timeout))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/share/squid-deb-proxy-client/apt-avahi-discover", line 128, in gather_hosts
    await asyncio.gather(*[h.time_connect() for h in hosts])
  File "/usr/share/squid-deb-proxy-client/apt-avahi-discover", line 51, in time_connect
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.17.0.1', 3142)
```

**Comment by jhonny-oliveira** [comment]
This was fixed here https://github.com/mvo5/squid-deb-proxy/pull/9, right?
